// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1560746651);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1560746771);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1560746531);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1560747011);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1560746891);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("extensions.blocklist.lastModified", "Fri, 14 Jun 2019 08:47:39 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1560746653);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190520110519");
user_pref("extensions.lastAppVersion", "60.7.0");
user_pref("extensions.lastPlatformVersion", "60.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("font.internaluseonly.changed", false);
user_pref("idle.lastDailyNotification", 1560746820);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "cf81d7ee-1904-499c-aeb7-a2b1d6e4a2d");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1560746823);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("services.blocklist.addons.checked", 1560746765);
user_pref("services.blocklist.clock_skew_seconds", 6);
user_pref("services.blocklist.gfx.checked", 1560746765);
user_pref("services.blocklist.last_etag", "\"1560643286328\"");
user_pref("services.blocklist.last_update_seconds", 1560746765);
user_pref("services.blocklist.onecrl.checked", 1560746765);
user_pref("services.blocklist.pinning.checked", 1560746765);
user_pref("services.blocklist.plugins.checked", 1560746765);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1560746823);
user_pref("toolkit.telemetry.cachedClientID", "59ffdb75-ef2b-4bfa-8b75-c977be0fb39d");
user_pref("toolkit.telemetry.previousBuildID", "20190520110519");
user_pref("toolkit.telemetry.prompted", 2);
